services:
  app:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "8000:8080"
    environment:
      BASE_URL: "http://localhost:8000"
      PORT: 8080
      MAX_ITEMS_COUNT: 10
      MAX_ITEM_LENGTH: 20
      MAX_WISHLISTS_PER_DAY: 3
      MAX_BODY_SIZE: 10K
      USE_IN_MEMORY_DB: "False"
      SQLITE_DB_NAME: "/sqlite_data/sqlite.db"
    volumes:
      - sqlite_data:/sqlite_data


volumes:
  sqlite_data: